- CHANGES.rst
- plone/app/portlets/exportimport/portlets.py
Portlet assignments can contain arbitrary data, but the exporter only covers the simple cases used by core. This change allows for Object and List fields to be exported properly, regardless of what they contain.
> Make exporting field definitions in assignments recursive, to handle complex data structures

- CHANGES.rst
- plone/app/portlets/portlets/login.pt
Read security settings from the registry instead of portal properties. This is part of work on the security control panel migration: https://github.com/plone/Products.CMFPlone/issues/216
This should be merged along with https://github.com/plone/Products.CMFPlone/pull/362
> Plip 10359 - Security Control Panel migration

- plone/app/portlets/tests/base.py
If not you get a warning and it adds it anyway.
Fixes https://github.com/plone/Products.CMFPlone/issues/501
> Subclass  ZopeTestCase.Functional

- plone/app/portlets/portlets/actions.pt
"section" is not a valid aria role, although it is a valid (and correct) html5 element. Role "menu" is best approximation of what the portlet does
> change role to be a valid one.

- CHANGES.rst
- plone/app/portlets/portlets/classic.pt
Need a sanity check on this one. Anything that previously referenced a global defines variable could be added the template referenced an instance of the classic portlet, so that we don't need to inject all of our globals in the base portlet template, right?
See also https://github.com/plone/Products.CMFPlone/issues/836
> Global defines will be removed in 5.0

- CHANGES.rst
- plone/app/portlets/portlets/navigation.py
> If 'currentFolderOnly', navigation portlet header link should go to current folder

- CHANGES.rst
- plone/app/portlets/portlets/rss.py
Unfortunately, I did not break up the two changes in two different PRs, but being quite small, I hope it is not necessary.
Change 1: Honour caching headers when getting rss requests.
Change 2: Remove the hard coded additional ten minute delay for polling rss feeds again.
Change 2 hard coded additional delays on error is a PITA if you use rss to tightly couple two internal systems and want a low delay of 1 minute only.
Otoh if you use it to get rss feeds from some random news site and don't change any polling settings, you have a default polling time of 100 minutes, on error 110 minutes, this is a bit of a joke.
Otoh if you use it to get rss feeds from some random news site and don't change any polling settings, you have a default polling time of 100 minutes, on error 110 minutes, this is …
> Use caching headers while getting rss, remove unconfigurable additional delay on errors

- CHANGES.rst
- plone/app/portlets/portlets/rss.pt
URL with special characters such as `&` will be HTML escaped (as `&amp;` for `&`) and cause the link to break.
removing `string:` from the tal expression resolves this.
> fix: links in RSS portlets when using special characters.

- CHANGES.rst
- plone/app/portlets/browser/templates/topbar-manage-portlets.pt
- setup.py
1) IMO for making optimal use of the jumplist, content should be loaded via Ajax. In this PR I added no JS and instead took advantage of existing [`setupAddDropdown` code](https://github.com/plone/plone.app.portlets/blob/master/plone/app/portlets/browser/manage-portlets.js#L151-L163) so managers open in a modal.
1.1) I did some tests and could add/edit/remove portlets inside the modals. I only noticed one inconsistency: editing a portlet closes the modal and redirects browser so after edition is saved or cancelled Plone doesn't return to the original accessed manager (i.e. `@@topbar-manage-portlets/plone.originalcolumn`). It's not that bad but If you think it's best I can add JS to update only current `#content` and thus discard the modals (in this case we should drop the related code …
> Fix #65: add jumplist between portlet managers

- CHANGES.rst
- plone/app/portlets/portlets/rss.pt
This happens when we use chameleon.
Backport from a fix by Gagaro:
https://github.com/plone/plone.app.portlets/commit/2f99af207d655d27ede4e4573324685718708765
> Fixed links in RSS portlets when they have special characters.

- CHANGES.rst
- plone/app/portlets/browser/manage-portlets.js
Fixes some console warnings but not the strange ``define is not a function`` errors I encounter currently :\
Different story: this pattern should better moved to mockup. Ref: https://github.com/plone/Products.CMFPlone/issues/1653
> Change plone-manage-portlets to use Patternslib base pattern pat-base.

- CHANGES.rst
- plone/app/portlets/portlets/navigation_recurse.pt
Problem can be seen in Plone 5.0.5 final, see: https://www.plone-demo.info/news/newsitem-9
> Use absolute source URL in navigation portlet's thumbnails

- plone/app/portlets/portlets/navigation_recurse.pt
Fix for the duplicated site id in the image absolute url. I didn't add a changelog cause this is an amendment to #79 which wasn't released. After this is merged I need to create another PR and amend #81 to target the 3.x branch.
> Navportlet absolute thumbnails

- CHANGES.rst
- plone/app/portlets/browser/adding.py
- plone/app/portlets/browser/editmanager.py
- plone/app/portlets/browser/formhelper.py
- plone/app/portlets/browser/z3cformhelper.py
- plone/app/portlets/tests/test_redirects.py
Also, made sure that all form views have a `referer` property: until now some did not have it, some had it as property, some had it as method.
> Apply security hotfix 20160830 for redirects. [2.5.x, Plone 4.3]

- CHANGES.rst
- plone/app/portlets/tests/test_utils.py
- plone/app/portlets/utils.py
Make sure, that ``utils.assignment_mapping_from_key`` traverses only to non-unicode paths.
OFS.traversable doesn't accept unicode paths.
/cc @davisagli - that issue came up with: https://github.com/plone/plone.portlets/commit/ec30810b6be108d4deb69585ab1b35c87d8e6838
doing ``u'/path'.encode('utf-8')`` should be Py3 forward compatible.
This problems occurs when trying to call ``@@render-portlet`` with a portlet hash.
> OFS.traversable cannot do unicode

- CHANGES.rst
- plone/app/portlets/tests/test_configuration.py
- setup.py
This is needed to get Plone 5.2 coredev buildout green again. After the Python 3 changes of `Products.GenericSetup` have been merged to master.
> Adapt tests to `Products.GenericSetup >= 2.0`.

- CHANGES.rst
- plone/app/portlets/browser/formhelper.py
- plone/app/portlets/tests/test_formextender.py
- setup.cfg
Portlet add and edit forms already extend AutoExtensibleForm from plone.autoform. (Added in 2014 in fc15814).
That means it is (before this PR) possible to extend portlet forms with a FormExtender.
But some portlet AddForms fail when creating the Assignment, if there is a FormExtender for the form, and the addform uses `Assignment(**data)` for creation instead of explicit parameters.
This PR fixes this by filtering away data values that does not come from the 'core' schema.
First define a schema and a formextender:
```
class IPortletCssClass(Interface):
""" Schema for portlet css class  """
css_class = schema.TextLine(
title=u'Portlet appearance',
required=False
)
class PortletCssClassFormExtender(FormExtender):
def update(self):
self.add(IPortletCssClass, prefix="portletcssclass")
``` …
> Fix for making the already existing FormExtender feature work

- CHANGES.rst
- plone/app/portlets/browser/formhelper.py
- plone/app/portlets/tests/test_formextender.py
- setup.cfg
Motivation is to be able to use this bugfix before Plone 5.2 is released. Eg. in 5.1.3
See #115 - This branch is a cherry-pick of those 2 commits.
> backport "Fix for making the already existing FormExtender feature work #115" to 4.3.x branch

- CHANGES.rst
- plone/app/portlets/browser/editmanager.py
```
Traceback (innermost last):
Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module Products.PDBDebugMode.runcall, line 70, in pdb_runcall
Module ZPublisher.Publish, line 48, in call_object
Module Products.Five.browser.metaconfigure, line 485, in __call__
Module Products.Five.browser.pagetemplatefile, line 125, in __call__
Module Products.Five.browser.pagetemplatefile, line 59, in __call__
Module zope.pagetemplate.pagetemplate, line 132, in pt_render
Module five.pt.engine, line 98, in __call__
Module z3c.pt.pagetemplate, line 163, in render
Module chameleon.zpt.template, line 261, in render
Module chameleon.template, line 171, in render
Module 4e3cb452b99b6db6631312f79196a6fb.py, line 337, in render
Module …
```
> Fix portlet types from removed code breaking @@manage-portlets:

- news/cmfplone-2882.bugfix
- plone/app/portlets/portlets/navigation.py
https://github.com/plone/plone.app.portlets/pull/new/issuse-cmfplone-2882
> Fixes for exception raised in navigation portlet by File with unknown content-type in mime registry

- CHANGES.rst
- plone/app/portlets/portlets/calendar.pt
- plone/app/portlets/portlets/calendar.py
Links in the portlet calendar were with ``&amp;`` which were not always interpreted by recent browsers.
Replaced them by standards '&'.
> Links in portlet calendar were broken

- news/155.bugfix
- setup.py
> Remove cyclic dependency with plone.app.event.

- news/161.feature
- plone/app/portlets/tests/test_formextender.py
Fix tests when using `z3c.form>=4.x`
> Compatibility with latest z3c.form

- news/177.bugfix
- plone/app/portlets/browser/manage.py
- plone/app/portlets/browser/templates/manage-content-type.pt
Fixes https://github.com/plone/Products.CMFPlone/issues/3795
plone_layout.getIcon was removed already. I'm not sure what the replacement is, but I guess it's not particularly important to show the content type icon on this page.
> Fix error on manage-content-type-portlets view

- news/+no-ajax-load.bugfix.rst
- plone/app/portlets/browser/manage.py
Related:
https://github.com/plone/Products.CMFPlone/pull/4188
https://github.com/plone/Products.CMFPlone/pull/4169
https://github.com/plone/plone.base/pull/85
https://github.com/plone/plonetheme.barceloneta/pull/404
https://github.com/plone/plone.app.portlets/pull/203
> Disable the use of the ajax main template for manage portlet views due to some special response parsing.
