CHANGES.rst
plone/app/portlets/portlets/actions.pt

Please see https://github.com/plone/mockup/pull/485

Rename pat-modal to pat-plone-modal.

---

CHANGES.rst
plone/app/portlets/browser/editmanager.py
plone/app/portlets/browser/manage-portlets.js
plone/app/portlets/browser/manage.py
plone/app/portlets/browser/templates/edit-manager-contextual.pt
plone/app/portlets/browser/templates/edit-manager-macros.pt
plone/app/portlets/browser/templates/edit-manager.pt
plone/app/portlets/browser/templates/manage-content-type.pt
plone/app/portlets/browser/templates/manage-contextual.pt
plone/app/portlets/browser/templates/manage-dashboard.pt
plone/app/portlets/browser/templates/manage-group-dashboard.pt
plone/app/portlets/browser/templates/manage-group.pt
plone/app/portlets/browser/traversal.py
plone/app/portlets/manager.py
plone/app/portlets/tests/testViewName.rst

moves portlet management js into a pattern. This makes editing portlets much easier by having less page reloads.

manage portlets js fixes

---

CHANGES.rst
plone/app/portlets/browser/manage.py
plone/app/portlets/browser/templates/edit-manager-macros.pt
plone/app/portlets/browser/templates/topbar-manage-portlets.pt
plone/app/portlets/interfaces.py

Fixes https://github.com/plone/Products.CMFPlone/issues/844

Fix single portlet manager management to not show other portlets on same page

---

CHANGES.rst
plone/app/portlets/portlets/navigation.py

If this is ok, I'll apply the same fix to plone.app.event, re: `getDefaultPage`.

Fixes plone/Products.CMFPlone#1019

---

plone/app/portlets/portlets/navigation.py

Sorry, I think my previous PR was incorrect.  This should do it.

Better resolution of deprecation warning for isDefaultPage.

---

CHANGES.rst
README.rst
plone/app/portlets/portlets/actions.pt
plone/app/portlets/portlets/language.pt
plone/app/portlets/portlets/login.pt
plone/app/portlets/portlets/navigation.pt
plone/app/portlets/portlets/news.pt
plone/app/portlets/portlets/recent.pt
plone/app/portlets/portlets/review.pt
plone/app/portlets/portlets/rss.pt
plone/app/portlets/portlets/search.pt
setup.py

Part of https://github.com/plone/Products.CMFPlone/issues/1430

Fix html validation

---

plone/app/portlets/browser/manage-portlets.js
plone/app/portlets/browser/templates/topbar-manage-portlets.pt

Fix jumplist across portlet managers (refs #66)

---

CHANGES.rst
plone/app/portlets/portlets/search.pt
plone/app/portlets/portlets/search.py

for https://github.com/plone/Products.CMFPlone/issues/1609

added pat-livesearch

---

CHANGES.rst
plone/app/portlets/portlets/actions.pt
plone/app/portlets/portlets/actions.py
plone/app/portlets/tests/test_actions_portlet.py

+ remove some Plone 3 compatibility code

add CSS class to actions portlet for easier styling

---

CHANGES.rst
plone/app/portlets/exportimport/portlets.py

With this pull request it would be easier to narrow down the errors location when importing portlets to Plone.

Better error messages for importing portlets

---

CHANGES.rst
plone/app/portlets/portlets/navigation_recurse.pt

Use absolute source URL in navigation portlet's thumbnails

---

plone/app/portlets/portlets/navigation_recurse.pt

Backport from #82. @thet, would you mind merging this one too?

Fix image url

---

CHANGES.rst
plone/app/portlets/portlets/navigation_recurse.pt
plone/app/portlets/tests/test_navigation_portlet.py

Fixes https://github.com/plone/plone.app.portlets/issues/93

Fix issue where navigation portlet ignored bottomLevel == 0

---

CHANGES.rst
plone/app/portlets/portlets/navigation_recurse.pt
plone/app/portlets/portlets/news.pt
plone/app/portlets/portlets/recent.pt
plone/app/portlets/portlets/review.pt
plone/app/portlets/portlets/review.py
setup.py

https://github.com/plone/Products.CMFPlone/issues/1483

Plip 1483 retina image scales

---

CHANGES.rst
plone/app/portlets/tests/base.py

see https://github.com/plone/Products.CMFPlone/issues/1882

remove unittest2 dependency

---

CHANGES.rst
plone/app/portlets/portlets/navigation.py
plone/app/portlets/portlets/navigation_recurse.pt
plone/app/portlets/portlets/news.pt
plone/app/portlets/portlets/news.py
plone/app/portlets/portlets/recent.pt
plone/app/portlets/portlets/recent.py
plone/app/portlets/portlets/review.pt
plone/app/portlets/portlets/review.py
plone/app/portlets/tests/profiles/testing/portlets.xml
plone/app/portlets/tests/test_configuration.py

Followup of https://github.com/plone/Products.CMFPlone/issues/1734

Cleanup of PLIP #1734

---

plone/app/portlets/portlets/recent.py
plone/app/portlets/portlets/review.py

further fixes for plip 1734-attribute-renames

---

CHANGES.rst
plone/app/portlets/tests/testMemberDashboard.rst

see https://github.com/plone/Products.CMFPlone/issues/2092

make work with merged plone.login

---

.gitattributes
CHANGES.rst
news/119.bugfix
news/121.bugfix
plone/app/portlets/testing.py
plone/app/portlets/tests/base.py
plone/app/portlets/tests/testDoctests.py
plone/app/portlets/tests/testMemberDashboard.rst
plone/app/portlets/tests/test_actions_portlet.py
plone/app/portlets/tests/test_context.py
plone/app/portlets/tests/test_namechooser.py
plone/app/portlets/tests/test_navigation_portlet.py
plone/app/portlets/tests/test_traversal.py
plone/app/portlets/tests/test_utils.py
pyproject.toml

And while at it initialize towncrier :+1: 
Fixes #121

Remove cruft

---

news/124.bugfix
plone/app/portlets/browser/utils.py
plone/app/portlets/tests/test_utils.py

Fix AttributeError in @@render-portlet

---

news/133.bugfix
plone/app/portlets/portlets/login.pt

fix default value for email msgid

---

news/130.bugfix
plone/app/portlets/portlets/review.pt

fix review portlet when show on the portal-root

---

news/128.bugfix
plone/app/portlets/portlets/navigation.pt

Remove role="navigation" from Navigation portlet.

---

news/3274.bugfix
plone/app/portlets/portlets/rss.py
plone/app/portlets/tests/atom_feed_maurits.xml
plone/app/portlets/tests/test_rss_portlet.py

From Products.PloneHotfix20210518.
See https://plone.org/security/hotfix/20210518/blind-ssrf-via-feedparser-accessing-an-internal-url

Only allow http and https urls in RSS portlet. [master / 6.0]

---

news/3274.bugfix
plone/app/portlets/portlets/rss.py
plone/app/portlets/tests/atom_feed_maurits.xml
plone/app/portlets/tests/test_rss_portlet.py

From Products.PloneHotfix20210518.
See https://plone.org/security/hotfix/20210518/blind-ssrf-via-feedparser-accessing-an-internal-url

Only allow http and https urls in RSS portlet. [4.4.x/5.2]

---

news/168.bugfix
plone/app/portlets/portlets/navigation.py

Use portal URL to build the mimetype icon url

---

CHANGES.rst
plone/app/portlets/portlets/login.pt

Updating the name on the button for the login portlet so it'll will work again ( Issue #132 )

Update login portlet button

---

news/132.bugfix
plone/app/portlets/portlets/login.pt

Here is the Pullrequest to hotfix the login portlet issue #132 in older versions (and hopefully this time with the right approach for the CHANGES.rst ;) @mauritsvanrees)

Issue 132 für 4.4.x version
